FORMAT: 1A
HOST: http://wsapi.jm-property.co.uk/v1/

# iMenzies
iMenzies API is for managing the *iMenzies* system.


# Group Credit Notes
## Get Customer Credit Notes [/customer/{customerid}/credit-note/{dateOrId}]
### GET
+ Response 200 (application/json)

        {
        "CreditNote" : {
            "CreditNoteId" : "1230409779",
            "CreditNoteDate" : "2013-03-20T00:00:00",
            "CreditNoteLines" : [{
                        "TitleId" : "353",
                        "IssueId" : "6003017",
                        "CopyNo" : "18/03/2013",
                        "Quantity" : 1,
                        "RetailPrice" : 0.50,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -11.75,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 0.38,
                        "NetValue" : 0.38,
                        "Currency" : "GBP",
                        "ObjId" : "NCR",
                        "SubObjId" : "SOL"
                    }, {
                        "TitleId" : "1831",
                        "IssueId" : "90013078",
                        "CopyNo" : "19/03/2013",
                        "Quantity" : 24,
                        "RetailPrice" : 0.40,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -9.28,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 7.37,
                        "NetValue" : 7.37,
                        "Currency" : "GBP",
                        "ObjId" : "NCR",
                        "SubObjId" : "SOL"
                    }
                ]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }],
            "statusCode" : 200
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        
        
        
# Group Customer range summary
## Get customer range summary [/customer/{customerid}/range-summary/{status}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["39084", "5538","42002"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }

## Get customer range summary by product type or status  [/customer/{customerid}/range-summary/{productTypeOrStatus}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["353", "1831", "1910"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }

## Get customer range summary by product type and status [/customer/{customerid}/range-summary/{productType}/{status}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["353", "1831", "1910"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }


        
# Group Customers
## GET /branches
Retrieve branches
+ Response 200 (application/json)

        {
          "Branches": [
            {
              "BranchId": "sample string 1",
              "ParentBranchId": "sample string 2",
              "Name": "sample string 3",
              "Street": "sample string 4",
              "City": "sample string 5",
              "Country": "sample string 6",
              "Postcode": "sample string 7"
            },
            {
              "BranchId": "sample string 1",
              "ParentBranchId": "sample string 2",
              "Name": "sample string 3",
              "Street": "sample string 4",
              "City": "sample string 5",
              "Country": "sample string 6",
              "Postcode": "sample string 7"
            },
            {
              "BranchId": "sample string 1",
              "ParentBranchId": "sample string 2",
              "Name": "sample string 3",
              "Street": "sample string 4",
              "City": "sample string 5",
              "Country": "sample string 6",
              "Postcode": "sample string 7"
            }
          ],
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }


        
## POST /customer/{customerid}/session
Retrieve session for user
+ Response 200 (application/json)

        {"SessionId":"1335100002","messages":[]}

+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }

# Group Customer
## Get customer data [/customer/{customerid}]
### GET
+ Response 200

        {
            "Customers" : [{
                    "CustomerId" : "0000119229",
                    "ContractBranch" : "560",
                    "MultipleCode" : "0",
                    "Name" : "Name",
                    "Street" : "Someone",
                    "City" : "City",
                    "Postcode" : "EH55 8ER",
                    "Country" : "GB",
                    "Phone" : "66658946",
                    "Email" : ""
                }
            ],
            "messages" : []
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }



## Get customer title range [/customer/{customerid}/range/]
### GET
+ Response 200 (application/json)

        {
        "range" : {
            "titles" : [{
                        "TitleNo" : "39084",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000390840001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }, {
                        "TitleNo" : "5538",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "MZ",
                                "StdOrdQty" : 6,
                                "issues" : [{
                                        "IssueNo" : "000000000055382042",
                                        "CopyNo" : "OCT 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }, {
                                        "IssueNo" : "000000000055382043",
                                        "CopyNo" : "NOV 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    },{
                        "TitleNo" : "42002",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000420020001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "titleCount" : 551
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        


## Get customer title range by titleId [/customer/{customerid}/range/{titleid}]
### GET
+ Response 200 (application/json)

        {
        "range" : {
            "titles" : [{
                        "TitleNo" : "000000000000039084",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000390840001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }, {
                        "TitleNo" : "000000000000005538",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "MZ",
                                "StdOrdQty" : 6,
                                "issues" : [{
                                        "IssueNo" : "000000000055382042",
                                        "CopyNo" : "OCT 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }, {
                                        "IssueNo" : "000000000055382043",
                                        "CopyNo" : "NOV 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    },{
                        "TitleNo" : "000000000000042002",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000420020001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "titleCount" : 551
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30", 
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        

        
## Get customer title range by product type [/customer/{customerid}/range/{productType}]
### GET
+ Response 200 (application/json)

        {
        "range" : {
            "titles" : [{
                        "TitleNo" : "39084",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000390840001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }, {
                        "TitleNo" : "5538",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "MZ",
                                "StdOrdQty" : 6,
                                "issues" : [{
                                        "IssueNo" : "000000000055382042",
                                        "CopyNo" : "OCT 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }, {
                                        "IssueNo" : "000000000055382043",
                                        "CopyNo" : "NOV 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    },{
                        "TitleNo" : "42002",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000420020001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "titleCount" : 551
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        

        

        

        
# Group Delivery Notes
## Get Customer delivery Notes [/customer/{customerid}/delivery-note/{date}]
### GET
+ Response 200 (application/json)

        {
        "DeliveryNote" : {
            "DeliveryNoteId" : "1230409779",
            "DeliveryNoteDate" : "2013-03-20T00:00:00",
            "DeliveryNoteLines" : [{
                        "TitleId" : "353",
                        "IssueId" : "6003017",
                        "CopyNo" : "18/03/2013",
                        "Quantity" : 1,
                        "RetailPrice" : 0.50,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -11.75,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 0.38,
                        "NetValue" : 0.38,
                        "Currency" : "GBP",
                        "OldPrice":0.32,
                        "NewPrice":0.32,
                        "RecallInfo" : "info",
                        "RecallFlag" : "flag"
                    }, {
                        "TitleId" : "343",
                        "IssueId" : "6023017",
                        "CopyNo" : "18/03/2013",
                        "Quantity" : 1,
                        "RetailPrice" : 0.50,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -11.75,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 0.38,
                        "NetValue" : 0.38,
                        "Currency" : "GBP",
                        "OldPrice":0.32,
                        "NewPrice":0.32,
                        "RecallInfo" : "info",
                        "RecallFlag" : "flag"
                    }
                ]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }],
            "statusCode" : 200
        }
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }


        



        


# Group Recall notes
## Get customer recall notes [/customer/{customerid}/recall-note/{date}]
### GET
+ Response 200 (application/json)

        
        {
            "RecallNotes" : [{
                    "RecallNoteId" : "6021798861",
                    "RecallNoteDate" : "2013-01-12T00:00:00",
                    "CollectionDate" : "2013-01-13T00:00:00",
                    "DocumentType" : "",
                    "RecallNoteLines" : [{
                            "TitleId" : "10000001288",
                            "IssueId" : "100000012880003",
                            "CopyNo" : "",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 0
                        }, {
                            "TitleId" : "10000001281",
                            "IssueId" : "100000012810001",
                            "CopyNo" : "",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 30
                        }, {
                            "TitleId" : "10000001277",
                            "IssueId" : "100000012770011",
                            "CopyNo" : "",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 0
                        }, {
                            "TitleId" : "10000000309",
                            "IssueId" : "100000003090003",
                            "CopyNo" : "",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 0
                        }
                    ]
                }, {
                    "RecallNoteId" : "6021809328",
                    "RecallNoteDate" : "2013-01-12T00:00:00",
                    "CollectionDate" : "2013-01-13T00:00:00",
                    "DocumentType" : "",
                    "RecallNoteLines" : [{
                            "TitleId" : "912",
                            "IssueId" : "9122962",
                            "CopyNo" : "12/01/2013",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 1
                        }, {
                            "TitleId" : "186",
                            "IssueId" : "1862962",
                            "CopyNo" : "12/01/2013",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 7
                        }, {
                            "TitleId" : "35092",
                            "IssueId" : "350921008",
                            "CopyNo" : "12/01/2013",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 51
                        }, {
                            "TitleId" : "41277",
                            "IssueId" : "412770052",
                            "CopyNo" : "11/01/2013",
                            "RetailPrice" : 0.0,
                            "Currency" : "",
                            "RecallQuantity" : 6
                        }
                    ]
                }
            ],
            "messages" : []
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        

        

# Group Titles
## GET /titles

+ Response 200 (application/json)

        [{
            "titleId":"char18",
            "titleText":"char40",
            "productType":"MAG"
        }]
        
        
## GET /titles/{id}
+ Response 200 (application/json)

        {
            "Titles":
            [{
                "TitleId":"char18",
                "TitleText":"char40",
                "ProductType":"MAG"
            }],
            "messages":[]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        

# Group Documents
## Get documents by ID [/customer/{customerid}/documents/{docid}]
### GET
+ Response 200 (application/json)

        {
            "DocumentOverview":
            {
                "DocOverviewLines":
                [
                    {
                        "DocId":"5630815544",
                        "DocDate":"2013-01-12",
                        "DocType":"CN"
                    }
                ]
            },
            "messages":
            []
        }

+ Response 404 (application/json)

        {
            "Message" : "Customer 11929 does not exist",
            "MessageDetail" : "KjuMoIlZ5r3X08002Z81PW 1 ZCX_CAPI_NO_CUSTOMER E"
        }
        
## Get documents by startdate and endate and document type [/customer/{customerId}/documents/{startDate}/{endDate}]
### GET 
+ Response 200 (application/json)

        {
            "DocumentOverview":
            {
                "DocOverviewLines":
                [
                    {
                        "DocId":"5630815544",
                        "DocDate":"2013-01-12",
                        "DocType":"CN"
                    }
                ]
            },
            "messages":
            []
        }

+ Response 404 (application/json)

        {
            "Message" : "Customer 11929 does not exist",
            "MessageDetail" : "KjuMoIlZ5r3X08002Z81PW 1 ZCX_CAPI_NO_CUSTOMER E"
        }
