FORMAT: 1A
HOST: http://wsapi.jm-property.co.uk/v1/

# iMenzies
iMenzies API is for managing the *iMenzies* system.


# Group Credit Note
## Get Customer Credit Note by Date or ID [/customer/{customerId}/credit-note/{dateOrId}]
### GET
+ Response 200 (application/json)

        {
        "CreditNote" : {
            "CreditNoteId" : "1230409779",
            "CreditNoteDate" : "2013-03-20T00:00:00",
            "CreditNoteLines" : [{
                        "TitleId" : "353",
                        "IssueId" : "6003017",
                        "CopyNo" : "18/03/2013",
                        "Quantity" : 1,
                        "RetailPrice" : 0.50,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -11.75,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 0.38,
                        "NetValue" : 0.38,
                        "Currency" : "GBP",
                        "ObjId" : "NCR",
                        "SubObjId" : "SOL"
                    }, {
                        "TitleId" : "1831",
                        "IssueId" : "90013078",
                        "CopyNo" : "19/03/2013",
                        "Quantity" : 24,
                        "RetailPrice" : 0.40,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -9.28,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 7.37,
                        "NetValue" : 7.37,
                        "Currency" : "GBP",
                        "ObjId" : "NCR",
                        "SubObjId" : "SOL"
                    }
                ]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }],
            "statusCode" : 200
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        
        
        
# Group Range Summary
## Get customer range summary [/customer/{customerId}/range-summary/{status}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["39084", "5538","42002"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }

## Get customer range summary by product type or status  [/customer/{customerId}/range-summary/{productTypeOrStatus}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["353", "1831", "1910"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }

## Get customer range summary by product type and status [/customer/{customerId}/range-summary/{productType}/{status}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["353", "1831", "1910"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }


# Group Final Delivery Note
## Get Final Delivery Notes by Date or Document ID [/customer/{customerId}/final-delivery-note/{dateOrDocumentId}]
### GET
+ Response 200 (application/json)

        {
          "DeliveryNote": {
            "DeliveryNoteDate": "2014-01-22T02:40:14.083107+00:00",
            "DeliveryNoteLines": [
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "Quantity": 4,
                "RetailPrice": 5.0,
                "RetailValue": 6.0,
                "DiscountPC": 7.0,
                "DiscountGR": 8.0,
                "TaxRate": 9.0,
                "TaxAmount": 10.0,
                "TotalCharges": 11.0,
                "NetValue": 12.0,
                "Currency": "sample string 13",
                "OldPrice": 14.0,
                "NewPrice": 15.0,
                "RecallInfo": "sample string 16",
                "RecallFlag": "sample string 17",
                "ObjId": "sample string 18",
                "SubObjId": "sample string 19"
              },
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "Quantity": 4,
                "RetailPrice": 5.0,
                "RetailValue": 6.0,
                "DiscountPC": 7.0,
                "DiscountGR": 8.0,
                "TaxRate": 9.0,
                "TaxAmount": 10.0,
                "TotalCharges": 11.0,
                "NetValue": 12.0,
                "Currency": "sample string 13",
                "OldPrice": 14.0,
                "NewPrice": 15.0,
                "RecallInfo": "sample string 16",
                "RecallFlag": "sample string 17",
                "ObjId": "sample string 18",
                "SubObjId": "sample string 19"
              },
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "Quantity": 4,
                "RetailPrice": 5.0,
                "RetailValue": 6.0,
                "DiscountPC": 7.0,
                "DiscountGR": 8.0,
                "TaxRate": 9.0,
                "TaxAmount": 10.0,
                "TotalCharges": 11.0,
                "NetValue": 12.0,
                "Currency": "sample string 13",
                "OldPrice": 14.0,
                "NewPrice": 15.0,
                "RecallInfo": "sample string 16",
                "RecallFlag": "sample string 17",
                "ObjId": "sample string 18",
                "SubObjId": "sample string 19"
              }
            ]
          },
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        


# Group Delivery Note
## Get Customer Delivery Note by Date or ID [/customer/{customerId}/delivery-note/{dateOrDocumentId}]
### GET
+ Response 200 (application/json)

        {
          "DeliveryNote": {
            "DeliveryNoteDate": "2014-01-22T02:42:09.4936048+00:00",
            "DeliveryNoteLines": [
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "Quantity": 4,
                "RetailPrice": 5.0,
                "RetailValue": 6.0,
                "DiscountPC": 7.0,
                "DiscountGR": 8.0,
                "TaxRate": 9.0,
                "TaxAmount": 10.0,
                "TotalCharges": 11.0,
                "NetValue": 12.0,
                "Currency": "sample string 13",
                "OldPrice": 14.0,
                "NewPrice": 15.0,
                "RecallInfo": "sample string 16",
                "RecallFlag": "sample string 17",
                "ObjId": "sample string 18",
                "SubObjId": "sample string 19"
              },
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "Quantity": 4,
                "RetailPrice": 5.0,
                "RetailValue": 6.0,
                "DiscountPC": 7.0,
                "DiscountGR": 8.0,
                "TaxRate": 9.0,
                "TaxAmount": 10.0,
                "TotalCharges": 11.0,
                "NetValue": 12.0,
                "Currency": "sample string 13",
                "OldPrice": 14.0,
                "NewPrice": 15.0,
                "RecallInfo": "sample string 16",
                "RecallFlag": "sample string 17",
                "ObjId": "sample string 18",
                "SubObjId": "sample string 19"
              },
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "Quantity": 4,
                "RetailPrice": 5.0,
                "RetailValue": 6.0,
                "DiscountPC": 7.0,
                "DiscountGR": 8.0,
                "TaxRate": 9.0,
                "TaxAmount": 10.0,
                "TotalCharges": 11.0,
                "NetValue": 12.0,
                "Currency": "sample string 13",
                "OldPrice": 14.0,
                "NewPrice": 15.0,
                "RecallInfo": "sample string 16",
                "RecallFlag": "sample string 17",
                "ObjId": "sample string 18",
                "SubObjId": "sample string 19"
              }
            ]
          },
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }

+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }

# Group Customer
## Get customer title data [/customer/{customerId}]
### GET
+ Response 200 (application/json)

        {
          "Customers": [
            {
              "CustomerId": "sample string 1",
              "ContractBranch": "sample string 2",
              "MultipleCode": "sample string 3",
              "Name": "sample string 4",
              "Street": "sample string 5",
              "City": "sample string 6",
              "Postcode": "sample string 7",
              "Country": "sample string 8",
              "Phone": "sample string 9",
              "Email": "sample string 10",
              "statement": true
            },
            {
              "CustomerId": "sample string 1",
              "ContractBranch": "sample string 2",
              "MultipleCode": "sample string 3",
              "Name": "sample string 4",
              "Street": "sample string 5",
              "City": "sample string 6",
              "Postcode": "sample string 7",
              "Country": "sample string 8",
              "Phone": "sample string 9",
              "Email": "sample string 10",
              "statement": true
            },
            {
              "CustomerId": "sample string 1",
              "ContractBranch": "sample string 2",
              "MultipleCode": "sample string 3",
              "Name": "sample string 4",
              "Street": "sample string 5",
              "City": "sample string 6",
              "Postcode": "sample string 7",
              "Country": "sample string 8",
              "Phone": "sample string 9",
              "Email": "sample string 10",
              "statement": true
            }
          ],
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }

        
# Group Allocation Note
## Get allocation note [/customer/{customerId}/allocation-note/{date}]
### GET
+ Response 200 (application/json)

        {
          "AllocationNote": {
            "AllocationNoteDate": "2014-01-22T02:47:05.7894439+00:00",
            "AllocationNoteLines": [
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "ObjId": "sample string 4",
                "SubObjId": "sample string 5",
                "RetailPrice": 6.0,
                "Currency": "sample string 7",
                "NewQuantity": 8,
                "SaleQuantity1": 9,
                "SaleQuantity2": 10,
                "SaleQuantity3": 11,
                "HonouredStatus": "sample string 12",
                "InfoText": "sample string 13"
              },
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "ObjId": "sample string 4",
                "SubObjId": "sample string 5",
                "RetailPrice": 6.0,
                "Currency": "sample string 7",
                "NewQuantity": 8,
                "SaleQuantity1": 9,
                "SaleQuantity2": 10,
                "SaleQuantity3": 11,
                "HonouredStatus": "sample string 12",
                "InfoText": "sample string 13"
              },
              {
                "TitleId": "sample string 1",
                "IssueId": "sample string 2",
                "CopyNo": "sample string 3",
                "ObjId": "sample string 4",
                "SubObjId": "sample string 5",
                "RetailPrice": 6.0,
                "Currency": "sample string 7",
                "NewQuantity": 8,
                "SaleQuantity1": 9,
                "SaleQuantity2": 10,
                "SaleQuantity3": 11,
                "HonouredStatus": "sample string 12",
                "InfoText": "sample string 13"
              }
            ]
          },
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        

# Group Invoice
## Get invoice by Date or ID [/customer/{customerId}/invoice/{dateOrId}]
### GET
+  Response 200 (application/json)

        {
          "Invoice": {
            "InvoiceDate": "2014-01-22T02:48:41.0550686+00:00",
            "InvoiceLines": [
              {
                "DeliveryNoteID": "sample string 1",
                "Day": "sample string 2",
                "Date": "2014-01-22T02:48:41.0550686+00:00",
                "RetailValue": 4.0,
                "NetValue": 5.0,
                "VATValue": 6.0,
                "Charges": 7.0,
                "Credits": 8.0,
                "GrossValue": 9.0,
                "Percent": 10.0,
                "ObjId": "sample string 11",
                "SubObjId": "sample string 12"
              },
              {
                "DeliveryNoteID": "sample string 1",
                "Day": "sample string 2",
                "Date": "2014-01-22T02:48:41.0550686+00:00",
                "RetailValue": 4.0,
                "NetValue": 5.0,
                "VATValue": 6.0,
                "Charges": 7.0,
                "Credits": 8.0,
                "GrossValue": 9.0,
                "Percent": 10.0,
                "ObjId": "sample string 11",
                "SubObjId": "sample string 12"
              },
              {
                "DeliveryNoteID": "sample string 1",
                "Day": "sample string 2",
                "Date": "2014-01-22T02:48:41.0550686+00:00",
                "RetailValue": 4.0,
                "NetValue": 5.0,
                "VATValue": 6.0,
                "Charges": 7.0,
                "Credits": 8.0,
                "GrossValue": 9.0,
                "Percent": 10.0,
                "ObjId": "sample string 11",
                "SubObjId": "sample string 12"
              }
            ],
            "InvoiceId": "sample string 1",
            "InvoiceWeekNo": "sample string 2",
            "InvoiceCurrency": "sample string 3"
          },
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }

+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        

# Group Document Overview
## Get documents by ID [/customer/{customerid}/documents/{docid}]
### GET
+ Response 200 (application/json)

        {
          "DocumentOverview": {
            "DocOverviewLines": [
              {
                "DocId": "sample string 1",
                "DocDate": "sample string 2",
                "DocType": "sample string 3"
              },
              {
                "DocId": "sample string 1",
                "DocDate": "sample string 2",
                "DocType": "sample string 3"
              },
              {
                "DocId": "sample string 1",
                "DocDate": "sample string 2",
                "DocType": "sample string 3"
              }
            ]
          },
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }

+ Response 404 (application/json)

        {
            "Message" : "Customer 11929 does not exist",
            "MessageDetail" : "KjuMoIlZ5r3X08002Z81PW 1 ZCX_CAPI_NO_CUSTOMER E"
        }
        
## Get documents by startdate and endate and document type [/customer/{customerId}/documents/{startDate}/{endDate}]
### GET 
+ Response 200 (application/json)

        {
          "DocumentOverview": {
            "DocOverviewLines": [
              {
                "DocId": "sample string 1",
                "DocDate": "sample string 2",
                "DocType": "sample string 3"
              },
              {
                "DocId": "sample string 1",
                "DocDate": "sample string 2",
                "DocType": "sample string 3"
              },
              {
                "DocId": "sample string 1",
                "DocDate": "sample string 2",
                "DocType": "sample string 3"
              }
            ]
          },
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }

+ Response 404 (application/json)

        {
            "Message" : "Customer 11929 does not exist",
            "MessageDetail" : "KjuMoIlZ5r3X08002Z81PW 1 ZCX_CAPI_NO_CUSTOMER E"
        }

# Group Titles
## Get Title [/titles/{titleId}]
### GET
+ Response 200 (application/json)
        
        {
          "Titles": [
            {
              "TitleId": "sample string 1",
              "TitleText": "sample string 2",
              "ProductType": "sample string 3",
              "Frequency": "sample string 4",
              "ProdHier": "sample string 5"
            },
            {
              "TitleId": "sample string 1",
              "TitleText": "sample string 2",
              "ProductType": "sample string 3",
              "Frequency": "sample string 4",
              "ProdHier": "sample string 5"
            },
            {
              "TitleId": "sample string 1",
              "TitleText": "sample string 2",
              "ProductType": "sample string 3",
              "Frequency": "sample string 4",
              "ProdHier": "sample string 5"
            }
          ],
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }

# Group Recall Note
## Get customer recall note by date [/customer/{customerId}/recall-note/{date}]
### GET
+ Response 200 (application/json)

        {
          "RecallNotes": [
            {
              "RecallNoteId": "sample string 1",
              "RecallNoteDate": "2014-01-22T02:53:58.7749879+00:00",
              "CollectionDate": "2014-01-22T02:53:58.7749879+00:00",
              "DocumentType": "sample string 4",
              "RecallNoteLines": [
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                },
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                },
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                }
              ]
            },
            {
              "RecallNoteId": "sample string 1",
              "RecallNoteDate": "2014-01-22T02:53:58.7749879+00:00",
              "CollectionDate": "2014-01-22T02:53:58.7749879+00:00",
              "DocumentType": "sample string 4",
              "RecallNoteLines": [
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                },
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                },
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                }
              ]
            },
            {
              "RecallNoteId": "sample string 1",
              "RecallNoteDate": "2014-01-22T02:53:58.7749879+00:00",
              "CollectionDate": "2014-01-22T02:53:58.7749879+00:00",
              "DocumentType": "sample string 4",
              "RecallNoteLines": [
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                },
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                },
                {
                  "TitleId": "sample string 1",
                  "IssueId": "sample string 2",
                  "CopyNo": "sample string 3",
                  "RetailPrice": 4.0,
                  "Currency": "sample string 5",
                  "RecallQuantity": 6
                }
              ]
            }
          ],
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }


# Group Range
## Get Customer's range [/customer/{customerId}/range?searchTerm={searchTerm}&startIndex={startIndex}&endIndex={endIndex}&status={status}]
### GET
+ Response 200 (application/json)

        {
          "Ranges": {
            "ActiveRange": {
              "Titles": [
                {
                  "TitleId": "sample string 1",
                  "Mandatory": true,
                  "Variants": [
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    }
                  ]
                },
                {
                  "TitleId": "sample string 1",
                  "Mandatory": true,
                  "Variants": [
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    }
                  ]
                },
                {
                  "TitleId": "sample string 1",
                  "Mandatory": true,
                  "Variants": [
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            "InactiveRange": {
              "Titles": [
                {
                  "TitleId": "sample string 1",
                  "Mandatory": true,
                  "Variants": [
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    }
                  ]
                },
                {
                  "TitleId": "sample string 1",
                  "Mandatory": true,
                  "Variants": [
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    }
                  ]
                },
                {
                  "TitleId": "sample string 1",
                  "Mandatory": true,
                  "Variants": [
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    },
                    {
                      "VariantType": "sample string 1",
                      "StdOrdQty": 2,
                      "Issues": [
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        },
                        {
                          "IssueId": "sample string 1",
                          "CopyNo": "sample string 2",
                          "PublicationDate": "2014-01-22T02:56:31.6260832+00:00",
                          "PackStatus": "sample string 4",
                          "DemandQty": 5,
                          "ExtrasOrderable": true
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          },
          "titleCount": 1,
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }

# Group User Session
## Retrieve session for user [/customer/{customerId}/session]
### POST
+ Response 200 (application/json)

        {
            "SessionId": "sample string 1",
            "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }

+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }


# Group Branch
## GET /branches
Retrieve branches
+ Response 200 (application/json)

        {
          "Branches": [
            {
              "BranchId": "sample string 1",
              "ParentBranchId": "sample string 2",
              "Name": "sample string 3",
              "Street": "sample string 4",
              "City": "sample string 5",
              "Country": "sample string 6",
              "Postcode": "sample string 7"
            },
            {
              "BranchId": "sample string 1",
              "ParentBranchId": "sample string 2",
              "Name": "sample string 3",
              "Street": "sample string 4",
              "City": "sample string 5",
              "Country": "sample string 6",
              "Postcode": "sample string 7"
            },
            {
              "BranchId": "sample string 1",
              "ParentBranchId": "sample string 2",
              "Name": "sample string 3",
              "Street": "sample string 4",
              "City": "sample string 5",
              "Country": "sample string 6",
              "Postcode": "sample string 7"
            }
          ],
          "messages": [
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            },
            {
              "LogId": "sample string 1",
              "LogItem": 2,
              "Category": "sample string 3",
              "Type": "sample string 4",
              "Text": "sample string 5"
            }
          ]
        }
        
+ Response 500 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:",
            "MessageDetail":"KfvXqYTTHM3X08002Z81PW 1 ZCX_CAPI_CRED_NOTE_NOT_FOUND E"
        }
        
+ Response 400 (application/json)

        {
            "Message":"Credit note not found for customer: 119229 and date: 15.01.2013 annd id:"
        }


        