FORMAT: 1A
HOST: http://www.google.com

# iMenzies
iMenzies API is for managing the *iMenzies* system.

# Orders
API Description for Orders

# Group Customers
## POST /users/register
Register a new user.
+ Request (application/json)

        [{"username":"username", "password":"password", "email":"e-mail"}]

+ Response 200 (application/json)
        
        [{"id":1}]

+ Response 409 (application/json)

        [{"code":1, "message":"Duplicate username"}]
        [{"code":2, "message":"Duplicate e-mail"}]

## POST /users/login
Login a user
+ Request (application/json)

        {"username":"username", "password":"password"}
        
+ Response 200 (application/json)
        
        {"id":"00112233", "created":"2013-11-20T10:45:35.511Z", "lastlogin":"2013-11-20T10:45:36.511Z", "email":"user@domain.com"}

+ Response 404 (application/json)

        {"code":10, "message":"User not found"}
        
+ Response 409 (application/json)

        {"code":11, "message":"Invalid password"}

## POST /users/changepassword
Change user password
+ Request (application/json)

        {"username":"username", "password":"password"}
        
+ Response 200 (application/json)

        {}

+ Response 404 (application/json)

        {"code":10, "message":"User not found"}
        
        
# Group Customer
## Get customer title range [/customer/{customerid}/range/]
### GET

+ Response 200 (application/json)

        {
        "range" : {
            "titles" : [{
                        "TitleNo" : "39084",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000390840001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }, {
                        "TitleNo" : "5538",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "MZ",
                                "StdOrdQty" : 6,
                                "issues" : [{
                                        "IssueNo" : "000000000055382042",
                                        "CopyNo" : "OCT 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }, {
                                        "IssueNo" : "000000000055382043",
                                        "CopyNo" : "NOV 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    },{
                        "TitleNo" : "42002",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000420020001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "titleCount" : 551
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }

## Get customer title range by titleId [/customer/{customerid}/range/{titleid}]
### GET

+ Response 200 (application/json)

        {
        "range" : {
            "titles" : [{
                        "TitleNo" : "000000000000039084",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000390840001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }, {
                        "TitleNo" : "000000000000005538",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "MZ",
                                "StdOrdQty" : 6,
                                "issues" : [{
                                        "IssueNo" : "000000000055382042",
                                        "CopyNo" : "OCT 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }, {
                                        "IssueNo" : "000000000055382043",
                                        "CopyNo" : "NOV 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    },{
                        "TitleNo" : "000000000000042002",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000420020001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "titleCount" : 551
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30", 
                "type":"char1",
                "text":"char220"
            }]
        }
        
## Get customer title range by product type [/customer/{customerid}/range/{productType}]
### GET

+ Response 200 (application/json)

        {
        "range" : {
            "titles" : [{
                        "TitleNo" : "39084",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000390840001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }, {
                        "TitleNo" : "5538",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "MZ",
                                "StdOrdQty" : 6,
                                "issues" : [{
                                        "IssueNo" : "000000000055382042",
                                        "CopyNo" : "OCT 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }, {
                                        "IssueNo" : "000000000055382043",
                                        "CopyNo" : "NOV 13",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    },{
                        "TitleNo" : "42002",
                        "Mandatory" : false,
                        "variants" : [{
                                "VariantType" : "Z7",
                                "StdOrdQty" : 0,
                                "issues" : [{
                                        "IssueNo" : "000000000420020001",
                                        "CopyNo" : "ONE SHOT",
                                        "PublicationDate" : "2013-01-01T00:00:00",
                                        "PackStatus" : "NP",
                                        "DemandQty" : 0,
                                        "ExtrasOrderable" : false
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "titleCount" : 551
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        
# Group Customer range summary
## Get customer range summary [/customer/{customerid}/range-summary/{status}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["39084", "5538","42002"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }

## Get customer range summary by product type and status  [/customer/{customerid}/range-summary/{productType}/{status}]
### GET
+ Response 200 (application/json)

        {
            "rangeSummary" : {
                "active" : ["353", "1831", "1910"],
                "inactive" : ["180", "182", "254"]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }]
        }
        

# Group Credit Notes
## Get Customer Credit Notes [/customer/{customerid}/credit-note/{date}]
### GET
+ Response 200 (application/json)

        {
        "CreditNote" : {
            "CreditNoteId" : "1230409779",
            "CreditNoteDate" : "2013-03-20T00:00:00",
            "CreditNoteLines" : [{
                        "TitleId" : "353",
                        "IssueId" : "6003017",
                        "CopyNo" : "18/03/2013",
                        "Quantity" : 1,
                        "RetailPrice" : 0.50,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -11.75,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 0.38,
                        "NetValue" : 0.38,
                        "Currency" : "GBP",
                        "ObjId" : "NCR",
                        "SubObjId" : "SOL"
                    }, {
                        "TitleId" : "1831",
                        "IssueId" : "90013078",
                        "CopyNo" : "19/03/2013",
                        "Quantity" : 24,
                        "RetailPrice" : 0.40,
                        "RetailValue" : 0.0,
                        "DiscountPC" : 0.0,
                        "DiscountGR" : -9.28,
                        "TaxRate" : 0.0,
                        "TaxAmount" : 0.0,
                        "TotalCharges" : 7.37,
                        "NetValue" : 7.37,
                        "Currency" : "GBP",
                        "ObjId" : "NCR",
                        "SubObjId" : "SOL"
                    }
                ]
            },
            "messages" : [{
                "logId":"char22",
                "logItem":22,
                "category":"char30",
                "type":"char1",
                "text":"char220"
            }],
            "statusCode" : 200
        }



# Group Titles
## GET /titles

+ Response 200 (application/json)

        [{
            "titleId":"char18",
            "titleText":"char40",
            "productType":"MAG"
        }]
        
## GET /titles/{id}
+ Response 200 (application/json)

        {
            "titleId":"char18",
            "titleText":"char40",
            "productType":"MAG"
        }
        
# Group Materials

# Group Orders

## Contracts Admin Collection [/admin/orders/contracts]
### List all Contracts [GET]
+ Response 200 (application/json)

        [{
            "id":1,
            "title":"Spiderman",
            "customer":{
                "id":1
            }
        },{
            "id":2,
            "title":"The Guardian",
            "customer":{
                "id":1
            }
        }]

## Contracts Admin Search [/admin/search/orders/contracts/{search}]
### Search for Contracts [GET]
Finds all contracts by specified search filter
+ Parameters
    + search (optional, `Superman`) ... Value to search for from contracts or customers. Has example value.

+ Response 200 (application/json)

        [{
            "id":1,
            "title":"Spiderman",
            "customer":{
                "id":1
            }
        },{
            "id":2,
            "title":"The Guardian",
            "customer":{
                "id":1
            }
        }]
        
## Contract Admin [/admin/orders/contracts/{id}]
### Retrieve contract [GET]
+ Parameters
    + id (required, `1`) ... Numeric `id` of the Contract to perform action with. Has example value.

+ Response 200 (application/json)

        [{
            "id":1,
            "title":"Spiderman",
            "customer":{
                "id":1
            }
        }]

### Edit a contract [POST]
Edits one contract
+ Parameters
    + id (required, `1`) ... Edits one contract as specified by `id`.

+ Request (application/json)

        [{
            "title":"Spiderman"
        }]

+ Response 201 (application/json)
    
        [{
            "title":"Spiderman"
        }]

### Removes a contract [DELETE]
+ Parameters
    + id (required, `1`) ... Numeric `id` of the Contract to perform action with. Has example value.
+ Response 204

## Contracts Collection [/orders/contracts]
### List all Contracts [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Spiderman"
        }, {
          "id": 2, "title": "The Guardian"
        }]

### Create an order [POST]
+ Request (application/json)

        { "title": "Superman" }

+ Response 201 (application/json)

        { "id": 3, "title": "Superman" }

## Contract [/orders/contracts/{id}]
A single Contract object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Contract to perform action with. Has example value.

### Retrieve a Contract [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "The Guardian" }

### Remove a Contract [DELETE]
+ Response 204
        

## Standing Orders Collection [/orders/standing]
### List all Standing Orders [GET]
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]

## Demand Collection [/orders/demand]
### List all demands [GET]
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]


## Changing Orders Collection [/orders/changing]
### List all changing orders [GET]
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]




# Group Claims
## Delivery Claims

### Delivery Claims [/claims/deliveries]
#### List all Delivery Claims [GET]
+ Response 200 (application/json)

        [{
            "id":1, "title":"Spiderman"
        },{
            "id":2, "title":"The Guardian"
        }]
    
#### Create new Delivery Claim [POST]
+ Request (application/json)

        {"id":1}
    
+ Response 201 (application/json)
    
        {"id":1}


### Single Delivery Claim [/claims/deliveries/{id}]
#### Retrieve a Delivery Claim [GET]
+ Response 200 (application/json)

        {"id":1}
    
#### Delete a Delivery Claim [DELETE]
+ Response 204


# Return Claims [/claims/returns]
### List all Returns Claims [GET]
+ Response 200 (application/json)

        [{
            "id":1, "title":"Spiderman"
        },{
            "id":2, "title":"The Guardian"
        }]

### Create new Returns Claim [POST]
+ Request (application/json)

        {"id":1}
    
+ Response 201 (application/json)
    
        {"id":1}


## Single Returns Claim [/claims/returns/{id}]
### Retrieve a Returns Claim [GET]
+ Response 200 (application/json)

        {"id":1}
    
### Delete a Returns Claim [DELETE]
+ Response 204

        
# Group Documents

## Delivery notes [/documents/deliveries]
### List all delivery notes [GET]
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]

## Credit advice notes [/documents/credits]
### List all credit advice notes [GET]
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]
        
        
## Allocation Advice notes [/documents/allocations]
### List all allocation advice notes [GET]
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]
        
## Final delivery notes [/documents/finaldeliveries]
### List all final delivery notes [GET]
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]
        
## Invoices [/documents/invoices]
### List all invoices
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]
        
## Recall notes [/documents/recalls]
### List all recall notes
+ Response 200 (application/json)

        [{
            "id":1
        },{
            "id":2
        }]
        
        